### ISSUE TITLE
Wrong configuration key

### ISSUE THREAD

**Issue by jughosta** [catberry/catberry-hello-world-handlebars#2]
https://github.com/catberry/catberry-hello-world-handlebars/blob/develop/server.js#L9

It should be `config.publicDirectoryPath`

**Comment by rdner** [comment]
Also, the same bug is in other templates for jade and dust.

**Comment by rdner** [comment]
Fixed in Handlebars template by fae76d94ebf07ff7b8260a312f0a9e889f161778

**Comment by rdner** [comment]
Fixed in Jade by https://github.com/catberry/catberry-hello-world-jade/commit/86d21b7aa9573047e89db661fbf32db3fe00df5c

**Comment by rdner** [comment]
Fixed in Dust by https://github.com/catberry/catberry-hello-world-dust/commit/71ffa885a663798e6e11a79046f508301e46e873

**Comment by rdner** [comment]
Fixed in GitHub Example App by https://github.com/catberry/catberry-example/commit/8b27d9d581a9ac00242c50618d8f950325074211
